# Generated by Django 3.2.25 on 2025-09-11 16:03

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstadoTroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('automatico', models.BooleanField(default=True)),
                ('troll', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventoScoringTroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('motivo', models.CharField(choices=[('carga_valores_distintos_a_confirmados', 'Carga valores distintos a los confirmados'), ('indica_problema_mesa_categoria_confirmada', 'Indica "problema" para una mesa/categoría con carga confirmada'), ('identificacion_attachment_distinta_a_confirmada', 'Identifica un attachment de una forma distinta a la confirmada'), ('problema_descartado', 'Se descarta un "problema" reportado por el usuario.'), ('marca_explicita_troll', 'Un usuario marca explitimamente a un fiscal como troll'), ('remocion_marca_troll', 'Se remueve la marca de troll a un fiscal'), ('carga_aceptada', 'Carga los valores aceptados'), ('identificacion_aceptada', 'Realiza una identificación con la decisión aceptada')], max_length=50)),
                ('automatico', models.BooleanField(default=True)),
                ('variacion', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
