# Generated by Django 3.2.25 on 2025-09-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adjuntos', '0002_initial'),
        ('fiscales', '0001_initial'),
        ('elecciones', '0001_initial'),
        ('antitrolling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoscoringtroll',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscales.fiscal'),
        ),
        migrations.AddField(
            model_name='eventoscoringtroll',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adjuntos.attachment'),
        ),
        migrations.AddField(
            model_name='eventoscoringtroll',
            name='fiscal_afectado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_scoring_troll', to='fiscales.fiscal'),
        ),
        migrations.AddField(
            model_name='eventoscoringtroll',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.mesa'),
        ),
        migrations.AddField(
            model_name='eventoscoringtroll',
            name='mesa_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.mesacategoria'),
        ),
        migrations.AddField(
            model_name='cambioestadotroll',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscales.fiscal'),
        ),
        migrations.AddField(
            model_name='cambioestadotroll',
            name='evento_disparador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antitrolling.eventoscoringtroll'),
        ),
        migrations.AddField(
            model_name='cambioestadotroll',
            name='fiscal_afectado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado_troll', to='fiscales.fiscal'),
        ),
    ]
