# Generated by Django 3.2.25 on 2025-09-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antitrolling', '0004_auto_20190922_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioestadotroll',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventoscoringtroll',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
