# Generated by Django 3.2.25 on 2025-09-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscales', '0001_initial'),
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncomputo',
            name='fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_computo', to='fiscales.fiscal'),
        ),
        migrations.AddField(
            model_name='circuito',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuitos', to='elecciones.seccion'),
        ),
        migrations.AddField(
            model_name='categoriaopcion',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.categoria'),
        ),
        migrations.AddField(
            model_name='categoriaopcion',
            name='opcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.opcion'),
        ),
        migrations.AddField(
            model_name='categoriageneral',
            name='eleccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.eleccion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='elecciones.categoriageneral'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.distrito'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='eleccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.eleccion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='opciones',
            field=models.ManyToManyField(related_name='categorias', through='elecciones.CategoriaOpcion', to='elecciones.Opcion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.seccion'),
        ),
        migrations.AddField(
            model_name='cargaoficialcontrol',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='elecciones.categoria'),
        ),
        migrations.AddField(
            model_name='carga',
            name='fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscales.fiscal'),
        ),
        migrations.AddField(
            model_name='carga',
            name='mesa_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='elecciones.mesacategoria'),
        ),
        migrations.AddField(
            model_name='agrupacioncircuitos',
            name='circuitos',
            field=models.ManyToManyField(related_name='agrupaciones', through='elecciones.AgrupacionCircuito', to='elecciones.Circuito'),
        ),
        migrations.AddField(
            model_name='agrupacioncircuitos',
            name='proyeccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrupaciones', to='elecciones.tecnicaproyeccion'),
        ),
        migrations.AddField(
            model_name='agrupacioncircuito',
            name='agrupacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.agrupacioncircuitos'),
        ),
        migrations.AddField(
            model_name='agrupacioncircuito',
            name='circuito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.circuito'),
        ),
        migrations.AlterUniqueTogether(
            name='votomesareportado',
            unique_together={('carga', 'opcion')},
        ),
        migrations.AlterUniqueTogether(
            name='mesacategoria',
            unique_together={('mesa', 'categoria')},
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('circuito', 'numero')},
        ),
        migrations.AddConstraint(
            model_name='configuracioncomputodistrito',
            constraint=models.UniqueConstraint(fields=('configuracion', 'distrito'), name='distrito_unico'),
        ),
        migrations.AddConstraint(
            model_name='configuracioncomputo',
            constraint=models.UniqueConstraint(fields=('nombre',), name='nombre_unico'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriaopcion',
            unique_together={('categoria', 'opcion')},
        ),
    ]
