# Generated by Django 3.2.25 on 2025-09-11 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adjuntos', '0001_initial'),
        ('fiscales', '0001_initial'),
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('estado', models.CharField(blank=True, choices=[('potencial', 'potencial'), ('descartado', 'descartado'), ('pendiente', 'pendiente'), ('en_curso', 'en curso'), ('resuelto', 'resuelto')], max_length=100, null=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='adjuntos.attachment')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='elecciones.mesa')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteDeProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_de_problema', models.CharField(choices=[('spam', 'La foto no es ni de un acta ni de un certificado. Parece subida maliciosamente.'), ('ilegible', 'La foto es de un acta pero no la puedo leer con claridad.'), ('falta_foto', 'La parte que es necesario cargar no está entre las fotos presentes.'), ('falta_identificador', 'El sistema no tiene la sección, circuito o mesa. Indicá el dato faltante en la descripción.'), ('falta_lista', 'El sistema no tiene una de las listas o agrupaciones que aparecen en el acta o certificado. Indicá el dato faltante en la descripción.'), ('otro', 'El problema no encaja en ninguna de las anteriores; describilo en la descripción.')], default='ilegible', max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_reporte_fake', models.BooleanField(default=False)),
                ('carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='elecciones.carga')),
                ('identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='adjuntos.identificacion')),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='problemas.problema')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscales.fiscal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
