# Generated by Django 3.2.25 on 2025-09-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adjuntos', '0001_initial'),
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioridadScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde_proporcion', models.PositiveIntegerField()),
                ('hasta_proporcion', models.PositiveIntegerField()),
                ('prioridad', models.PositiveIntegerField(null=True)),
                ('hasta_cantidad', models.PositiveIntegerField(null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prioridades', to='elecciones.categoria')),
                ('seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prioridades', to='elecciones.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='ColaCargasPendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True)),
                ('numero_carga', models.PositiveIntegerField(default=1)),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adjuntos.attachment')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.distrito')),
                ('mesa_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.mesacategoria')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.seccion')),
            ],
            options={
                'verbose_name': 'Cola de Identificaciones y Cargas pendientes',
                'verbose_name_plural': 'Cola de Identificaciones y Cargas pendientes',
            },
        ),
        migrations.AddIndex(
            model_name='colacargaspendientes',
            index=models.Index(fields=['distrito', 'orden'], name='orden_distrito'),
        ),
        migrations.AddIndex(
            model_name='colacargaspendientes',
            index=models.Index(fields=['seccion', 'orden'], name='orden_seccion'),
        ),
        migrations.AlterUniqueTogether(
            name='colacargaspendientes',
            unique_together={('attachment', 'numero_carga'), ('mesa_categoria', 'numero_carga')},
        ),
    ]
