# Generated by Django 3.2.25 on 2025-09-11 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adjuntos', '0001_initial'),
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', model_utils.fields.StatusField(choices=[('IMPORTADO', 'IMPORTADO'), ('AUTOCONFIRMADO', 'AUTOCONFIRMADO'), ('PRE-INSCRIPTO', 'PRE-INSCRIPTO'), ('CONFIRMADO', 'CONFIRMADO'), ('DECLINADO', 'DECLINADO')], default='PRE-INSCRIPTO', max_length=100, no_check_for_status=True)),
                ('notas', models.TextField(blank=True, help_text='Notas internas, no se muestran')),
                ('codigo_confirmacion', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email_confirmado', models.BooleanField(default=False)),
                ('apellido', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('tipo_dni', models.CharField(choices=[('DNI', 'DNI'), ('CI', 'CI'), ('LE', 'LE'), ('LC', 'LC')], default='DNI', max_length=3)),
                ('dni', models.CharField(blank=True, max_length=15, null=True)),
                ('puntaje_scoring_troll', models.IntegerField(default=0)),
                ('troll', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('referente_certeza', models.PositiveIntegerField(default=100, help_text='El código no era exacto?')),
                ('referencia_confirmada', models.BooleanField(default=False)),
                ('referente_nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('referente_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('referido_por_codigos', models.CharField(blank=True, max_length=250, null=True)),
                ('ingreso_alguna_vez', models.BooleanField(default=False)),
                ('asignacion_ultima_tarea', models.DateTimeField(blank=True, null=True)),
                ('attachment_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_asignado', to='adjuntos.attachment')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal', to='elecciones.distrito')),
                ('distrito_afin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_afin', to='elecciones.distrito')),
                ('mesa_categoria_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_asignado', to='elecciones.mesacategoria')),
                ('referente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to='fiscales.fiscal')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal', to='elecciones.seccion')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fiscales',
                'unique_together': {('tipo_dni', 'dni')},
            },
        ),
        migrations.CreateModel(
            name='CodigoReferido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codigo', models.CharField(help_text='Código con el que el fiscal puede referir a otres', max_length=4, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_de_referidos', to='fiscales.fiscal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
