# Generated by Django 3.2.25 on 2025-09-11 16:03

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('sin_identificar', 'sin identificar'), ('identificada', 'identificada'), ('problema', 'problema')], default='sin_identificar', max_length=100, no_check_for_status=True)),
                ('mimetype', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='attachments/', width_field='width')),
                ('foto_edited', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='attachments/edited', width_field='width')),
                ('foto_digest', models.CharField(max_length=128, unique=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('cant_fiscales_asignados', models.PositiveIntegerField(default=0)),
                ('cant_asignaciones_realizadas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CSVTareaDeImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('csv_file', models.FileField(upload_to='csv/')),
                ('status', model_utils.fields.StatusField(choices=[('pendiente', 'pendiente'), ('en_progreso', 'en_progreso'), ('procesado', 'procesado')], default='pendiente', max_length=100, no_check_for_status=True)),
                ('errores', models.TextField(blank=True, default=None, null=True)),
                ('mesas_total_ok', models.PositiveIntegerField(default=0)),
                ('mesas_parc_ok', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tarea de importación de CSV',
                'verbose_name_plural': 'Tareas de importación de CSVs',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('from_address', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('title', models.CharField(max_length=150)),
                ('uid', models.PositiveIntegerField()),
                ('message_id', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('identificada', 'identificada'), ('problema', 'problema')], default='identificada', max_length=100, no_check_for_status=True)),
                ('source', model_utils.fields.StatusField(choices=[('web', 'web'), ('csv', 'csv'), ('telegram', 'telegram')], default='web', max_length=100, no_check_for_status=True)),
                ('tomada_por_consolidador', models.DateTimeField(blank=True, default=None, null=True)),
                ('procesada', models.BooleanField(default=False)),
                ('invalidada', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
