# Generated by Django 3.2.25 on 2025-09-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adjuntos', '0001_initial'),
        ('fiscales', '0001_initial'),
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preidentificacion',
            name='circuito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.circuito'),
        ),
        migrations.AddField(
            model_name='preidentificacion',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.distrito'),
        ),
        migrations.AddField(
            model_name='preidentificacion',
            name='fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscales.fiscal'),
        ),
        migrations.AddField(
            model_name='preidentificacion',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.seccion'),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identificaciones', to='adjuntos.attachment'),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='fiscal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fiscales.fiscal'),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identificaciones', to='elecciones.mesa'),
        ),
        migrations.AddField(
            model_name='csvtareadeimportacion',
            name='fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscales.fiscal'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adjuntos.email'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='identificacion_testigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_testigo', to='adjuntos.identificacion'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='elecciones.mesa'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='adjuntos.attachment'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='pre_identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment', to='adjuntos.preidentificacion'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_subidos', to='fiscales.fiscal'),
        ),
    ]
